// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    partial class AnimalShelterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Size")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Species")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Type")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Gender = "Male",
                            Name = "Zeus",
                            Size = "Large",
                            Species = "German Shepherd",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalId = 2,
                            Gender = "Male",
                            Name = "Poseidon",
                            Size = "Large",
                            Species = "Rottweiler",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalId = 3,
                            Gender = "Male",
                            Name = "Hades",
                            Size = "Large",
                            Species = "Doberman",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalId = 4,
                            Gender = "Female",
                            Name = "Jones",
                            Size = "Tiny",
                            Species = "Chihuahua",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalId = 5,
                            Gender = "Female",
                            Name = "Rose",
                            Size = "Medium",
                            Species = "Bulldog",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalId = 6,
                            Gender = "Female",
                            Name = "Swift",
                            Size = "Tiny",
                            Species = "Persian",
                            Type = "Cat"
                        },
                        new
                        {
                            AnimalId = 7,
                            Gender = "Male",
                            Name = "Bonkers",
                            Size = "Tiny",
                            Species = "Siamese",
                            Type = "Cat"
                        },
                        new
                        {
                            AnimalId = 8,
                            Gender = "Female",
                            Name = "Jordan",
                            Size = "Tiny",
                            Species = "Siberian",
                            Type = "Cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
